import { ChatProvider } from "@/contexts/ChatContext";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Projeto Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ChatProvider>{children}</ChatProvider>
      </body>
    </html>
  );
}
