import { UserProvider } from "@/contexts/UserContext";
import "./globals.css";
import type { Metadata } from "next";
import { ChatProvider } from "@/contexts/ChatContext";

export const metadata: Metadata = {
  title: "Projeto Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <ChatProvider>
            {children}
          </ChatProvider>
        </UserProvider>
      </body>
    </html>
  );
}
